# arcella/arcella-fs-utils/Cargo.toml
[package]
name = "arcella-fs-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Arcella filesystem utils"

[dependencies]
arcella-types = { path = "../arcella-types" }
dirs =  { workspace = true }
futures =  { workspace = true }
thiserror =  { workspace = true }
indexmap =  { workspace = true }
ordered-float =  { workspace = true }
tokio =  { workspace = true }
toml_edit =  { workspace = true }
uuid =  { workspace = true }

[dev-dependencies]
tempfile = "3.23.0"
tokio = { workspace = true, features = ["full"] }
